export const ADD_MARKDOWN = 'ADD_MARKDOWN';
export const DEL_MARKDOWN = 'DEL_MARKDOWN';
export const UPDATE_MARKDOWN = 'UPDATE_MARKDOWN';
export const SELECT_CURRENT_MARKDOWN = 'SELECT_CURRENT_MARKDOWN';
export const UPDATE_CURRENT_MARKDOWN = 'UPDATE_CURRENT_MARKDOWN';
